version: '3.8'

services:
  crawl4ai-agent:
    build: .
    image: crawl4ai-agent:latest
    container_name: crawl4ai-agent
    env_file: .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - crawl4ai-network

networks:
  crawl4ai-network:
    driver: overlay
    attachable: true 